name: jtjs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  amap_flutter_map: ^3.0.0
  amap_flutter_location: ^3.0.0
  amap_flutter_base: ^3.0.0
  permission_handler: ^10.2.0
  dio: ^4.0.6
  url_launcher: ^6.1.7
  flutter_speed_dial: ^6.2.0
  flutter_picker: 1.1.5
    # 弹框 https://pub.dev/packages/fluttertoast#-installing-tab-
  fluttertoast: ^7.0.4
    # 时间格式转换 https://pub.dev/packages/date_format
  date_format: 1.0.8
  flutter_cupertino_datetime_picker: ^3.0.0
  #UI库
  getwidget: ^3.0.1
#  拟态风格获取
  flutter_neumorphic: ^3.0.3
  #GETX
  get: ^4.6.5
  http: ^0.13.5
  socket_io_client: ^2.0.1
  via_logger: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: oppoSansBold
      fonts:
        - asset: assets/fonts/OPlusSans3-Bold.ttf
    - family: oppoSansExtraLight
      fonts:
        - asset: assets/fonts/OPlusSans3-ExtraLight.ttf
    - family: oppoSansMedium
      fonts:
        - asset: assets/fonts/OPlusSans3-Medium.ttf
    - family: oppoSansRegular
      fonts:
        - asset: assets/fonts/OPlusSans3-Regular.ttf